import { ProductType } from "@/pasteTypes/product";

export const Products: ProductType[] = [
  {
    id: 1,
    category: "Roupa",
    nameProduct: "Camisa",
    type: "Ralph Lauren",
    titleLink: "polo-ralph-lauren",
    gender: "M",
    title: "Polo Ralph Lauren",
    description: "",
    mainImage: "images/polo-a-1.webp",
    secondaryImages: [
      {id: 0, link:"images/polo-a-1.webp"},
      {id: 1, link:"images/polo-a-2.webp"},
      {id: 2, link:"images/polo-a-3.webp"},
      {id: 3, link:"images/polo-a-4.webp"},
      {id: 4, link:"images/polo-a-5.webp"}
      
    ],
    brand: "Polo",
    predominantColor: ["Azul-marinho", "azul"],
    secondaryColor: [],
    sizeAvailable: ["P", "M", "GG", "G"],
    price: 859.99,
    discount: {
      disc: true,
      Pct: 23,
      offPct: new Date("2024-06-08"),
    },
    hashtags: [
      "Polo",
      "Camisa",
      "Camisa Masculina",
      "Masculina",
      "Azul",
      "Azul-marinho",
      "Camisa com ziper",
      "Desconto",
    ],
    depleted: false,
  },
  {
    id: 2,
    category: "Calçados",
    nameProduct: "Tênis",
    type: "Basquete Buzzer",
    titleLink: "tenis-under-armour-basquete-buzzer-preto-dourado",
    gender: "M",
    brand: "Under",
    title: "Tênis Under Armour Basquete Buzzer",
    description: "",
    mainImage: "images/tenis-a-1.webp",
    secondaryImages: [
      {id: 0, link:"images/tenis-a-1.webp"},
      {id: 1, link:"images/tenis-a-2.webp"},
      {id: 2, link:"images/tenis-a-3.webp"},
      {id: 3, link:"images/tenis-a-4.webp"},

    ],
    predominantColor: ["Preto", "Dourado"],
    secondaryColor: ["Branco", "Vermelho"],
    sizeAvailable: ["39", "41", "42", "43", "44", "45", "46", "47", "48"],
    price: 299.99,
    discount: {
      disc: false,
      Pct: undefined,
      offPct: undefined,
    },
    hashtags: [
      "Under",
      "Under Armour",
      "Tênis",
      "Under Armour Basquete Buzzer",
      "Masculino",
      "Preto",
      "Dourado",
      "Dia a Dia",
      "Barato",
      "Barato",
      "Pés grandes",
      "Basquete",
    ],
    depleted: false,
  },
  {
    id: 3,
    category: "Calçados",
    nameProduct: "Tênis",
    type: "Air Max Plus",
    titleLink: "tenis-nike-air-max-plus-masculino",
    brand: "Nike",
    gender: "M",
    title: "Tênis Nike Air Max Plus Masculino",
    description: "",
    mainImage: "images/tenis-b-1.avif",
    secondaryImages: [
      {id: 0, link:"images/tenis-b-1.avif"},
      {id: 1, link:"images/tenis-b-2.avif"},
      {id: 2, link:"images/tenis-b-3.avif"},
      {id: 3, link:"images/tenis-b-4.avif"},
    ],
    predominantColor: ["Preto", "Verde"],
    secondaryColor: ["Branco"],
    sizeAvailable: ["37", "39", "39.5", "40", "41", "42", "43", "44", "45"],
    price: 1299.99,
    discount: {
      disc: true,
      Pct: 31,
      offPct: undefined,
    },
    hashtags: [
      "Nike",
      "Air",
      "Max",
      "Plus",
      "Preto",
      "Tênis",
      "Tênis Nike Air Max Plus",
      "Masculino",
      "Alto",
      "Verde",
      "casual",
      "Barato",
      "Promoção",
      "Estilo"
    ],
    depleted: false,
  },
  {
    id: 4,
    category: "Roupa",
    nameProduct: "Calça Jeans",
    type: "Sarja Cintura Alta",
    titleLink: "hno-calca-jeans",
    brand: "HNO",
    gender: "F",
    title: "HNO Jeans",
    description: "",
    mainImage: "images/calca-a-1.webp",
    secondaryImages: [
      {id: 0, link:"images/calca-a-1.webp"},
      {id: 1, link:"images/calca-a-2.webp"},
      {id: 2, link:"images/calca-a-3.webp"},
      {id: 3, link:"images/calca-a-4.webp"}
    ],
    predominantColor: ["Verde"],
    secondaryColor: [],
    sizeAvailable: ["34", "36", "40", "42", "44"],
    price: 199.90,
    discount: {
      disc: true,
      Pct: 50,
      offPct: new Date("2024-06-10"),
    },
    hashtags: [
      "calça",
      "Feminino",
      "Verde",
      "Calça curta",
      "Calça feminina",
      "Sarja Cintura Alta",
      "Estilo",
      "liquidação",
      "Apertada",
      "Sair",
      "Promoção",
      "Linda",
    ],
    depleted: false,
  },
  {
    id: 5,
    category: "Roupa",
    nameProduct: "Vestido",
    type: "FARM Midi Fenda",
    titleLink: "vestido-farm-midi",
    brand: "FARM",
    gender: "F",
    title: "Vestido FARM Midi",
    description: "Vestido FARM Midi Fenda Lateral Verde",
    mainImage: "images/vestido-a-1.webp",
    secondaryImages: [
      {id: 0, link:"images/vestido-a-1.webp"},
      {id: 1, link:"images/vestido-a-2.webp"},
    ],
    predominantColor: ["Verde", "Roxo"],
    secondaryColor: [
      "Vermelho",
      "Branco",
    ],
    sizeAvailable: ["PP", "P", "M", "G", "GG"],
    price: 629.00,
    discount: {
      disc: false,
      Pct: undefined,
      offPct: undefined,
    },
    hashtags: [
      "Vestido",
      "Feminino",
      "Verde",
      "Vestido Longo",
      "Vestido feminina",
      "Farma",
      "Lateral verde",
      "Colorido",
      "Esbotado",
      "Chama atenção",
      "Flores",
      "Vestido de Flores",
      "Linda",
    ],
    depleted: false,
  },




  {
    id: 6,
    category: "Roupa",
    nameProduct: "T-Shirt",
    type: "Casual",
    titleLink: "t-shirt-casual",
    gender: "U",
    title: "Comfortable Cotton T-Shirt",
    description: "A comfortable and stylish cotton t-shirt available in multiple colors.",
    mainImage: "https://example.com/images/tshirt_main.jpg",
    secondaryImages: [
      { id: 1, link: "https://example.com/images/tshirt_main.jpg", alt: "Main image of T-Shirt"},
      { id: 2, link: "https://example.com/images/tshirt_side.jpg", alt: "T-Shirt front view" },
      { id: 3, link: "https://example.com/images/tshirt_back.jpg", alt: "T-Shirt back view" },
    ],
    brand: "Brand A",
    predominantColor: ["Blue", "White"],
    secondaryColor: ["Red"],
    sizeAvailable: ["S", "M", "L", "XL"],
    price: 29.99,
    discount: {
      disc: true,
      Pct: 10,
      offPct: new Date('2024-07-01')
    },
    hashtags: ["#cotton", "#tshirt", "#casual"],
    depleted: false,
  },
  {
    id: 7,
    category: "Roupa",
    nameProduct: "Smartphone",
    titleLink: "smartphone",
    gender: "U",
    title: "Latest Model Smartphone",
    description: "A high-performance smartphone with the latest features and technology.",
    mainImage: "https://example.com/images/smartphone_main.jpg",
    secondaryImages: [
      { id: 1, link: "https://example.com/images/smartphone_main.jpg", alt: "Main image of Smartphone" },
      { id: 2, link: "https://example.com/images/smartphone_side.jpg", alt: "Smartphone front view" },
      { id: 3, link: "https://example.com/images/smartphone_back.jpg", alt: "Smartphone back view" },
    ],
    brand: "Brand B",
    predominantColor: ["Black"],
    secondaryColor: ["Silver"],
    sizeAvailable: [],
    price: 699.99,
    discount: {
      disc: false,
    },
    hashtags: ["#smartphone", "#electronics", "#latest"],
    depleted: false,
  },
  {
    id: 8,
    category: "Roupa",
    nameProduct: "Fiction Novel",
    titleLink: "fiction-novel",
    gender: "U",
    title: "Bestselling Fiction Novel",
    description: "A gripping fiction novel that keeps you on the edge of your seat.",
    mainImage: "https://example.com/images/book_main.jpg",
    secondaryImages: [
      { id: 1, link: "https://example.com/images/book_main.jpg", alt: "Main image of Fiction Novel" },
      { id: 2, link: "https://example.com/images/book_cover.jpg", alt: "Book cover" },
      { id: 3, link: "https://example.com/images/book_back.jpg", alt: "Book back cover" },
    ],
    brand: "Brand C",
    predominantColor: ["Green"],
    secondaryColor: ["White"],
    sizeAvailable: [],
    price: 19.99,
    discount: {
      disc: true,
      Pct: 15,
      offPct: new Date('2024-06-30')
    },
    hashtags: ["#books", "#fiction", "#bestseller"],
    depleted: false,
  },
  {
    id: 9,
    category: "Roupa",
    nameProduct: "Running Shoes",
    type: "Sportswear",
    titleLink: "running-shoes",
    gender: "U",
    title: "High-Performance Running Shoes",
    description: "Lightweight and durable running shoes designed for maximum comfort.",
    mainImage: "https://example.com/images/shoes_main.jpg",
    secondaryImages: [
      { id: 1, link: "https://example.com/images/shoes_main.jpg", alt: "Main image of Running Shoes" },
      { id: 2, link: "https://example.com/images/shoes_side.jpg", alt: "Running shoes side view" },
      { id: 3, link: "https://example.com/images/shoes_top.jpg", alt: "Running shoes top view" },
    ],
    brand: "Brand D",
    predominantColor: ["Black"],
    secondaryColor: ["Red"],
    sizeAvailable: ["8", "9", "10", "11"],
    price: 89.99,
    discount: {
      disc: false,
    },
    hashtags: ["#sports", "#running", "#shoes"],
    depleted: false,
  },
];
